Repository programmers-kdt-full-stack-3rd/community-board, pull requests merged in 2024-09, with the labels that each got.

#200 [FIX-BE] 사용자 로그 페이지에서 해당 유저 닉네임이 나오도록 수정
  client/src/page/Admin/AdminUserLogPage.tsx
  server/controller/admin_controller.ts
Labels: bug, back-end

#213 🐛 [fix] : 로그 아웃 -> 채팅 관련 state 초기화 + 메인 페이지로 이동
  client/src/component/Header/Header.tsx
  client/src/state/ChatRoomStore.ts
Labels: front-end

#201 [BE] 게시글 비공개기능 구현
  server/controller/posts_controller.ts
  server/db/context/posts_context.ts
Labels: back-end

#212 [Feature] 회원 가입 page 고도화
  client/src/component/User/DuplicationCheckButton.tsx
  client/src/component/User/EmailForm.tsx
  client/src/component/User/InputField.tsx
  client/src/component/User/InputForm.tsx
  client/src/component/User/NicknameForm.tsx
  client/src/component/User/PasswordForm.tsx
  client/src/component/User/SubmitButton.tsx
  client/src/component/User/css/InputField.css.ts
  client/src/component/User/css/SubmitButton.css.ts
  client/src/page/User/Join.tsx
  client/src/page/User/Login.tsx
  client/src/page/User/ProfileUpdate.tsx
  client/src/page/User/constants/constants.ts
Labels: front-end

#203 ✨ [feat] : docker에 mariadb 띄우기 + 자동으로 db 세팅
  .gitignore
  server/db/context/chats_context.ts
  server/db/context/comments_context.ts
  server/db/context/oauth_context.ts
  server/db/context/posts_context.ts
  server/db/context/stats_context.ts
  server/db/context/users_context.ts
  server/db/mapper/posts_mapper.ts
  server/db/mapper/users_mapper.ts
  server/db/sql/10_user_log_categories.sql
  server/db/sql/4_comments.sql
  server/db/sql/setup_rbac.sql
  sql/01_roles.sql
  sql/02_users.sql
  sql/03_posts.sql
  sql/04_comments.sql
  sql/05_chats.sql
  sql/06_refresh_tokens.sql
  sql/07_oauth.sql
  sql/08_permissions.sql
  sql/09_role_permission.sql
  sql/10_user_log_categories.sql
  sql/11_user_logs.sql
  sql/docker-compose.yaml
Labels: docker, database

#219 [feat] 공용 인터페이스 & 맵핑 함수
  .gitignore
  server/controller/admin_controller.ts
  server/controller/likes_controller.ts
  server/controller/oauth_controller.ts
  server/db/context/likes_context.ts
  server/db/context/logs_context.ts
  server/db/context/oauth_context.ts
  server/db/context/posts_context.ts
  server/db/context/roles_permission_context.ts
  server/db/context/stats_context.ts
  server/db/context/users_context.ts
  server/db/mapper/logs_mapper.ts
  server/db/mapper/posts_mapper.ts
  server/db/mapper/stats_mapper.ts
  server/db/mapper/users_mapper.ts
  server/db/model/logs.ts
  server/db/model/posts.ts
  server/db/model/stats.ts
  server/utils/oauth/constants.ts
  server/utils/oauth/oauth.ts
  server/utils/validations/likes/constants.ts
  server/utils/validations/likes/like.ts
  server/utils/validations/oauth/constants.ts
  server/utils/validations/oauth/oauth.ts
  shared/chat/chat_api.ts
  shared/chat/chat_mapper.ts
  shared/chat/chats.ts
  shared/chats/message.ts
  shared/community/admin/admin.ts
  shared/community/admin/admin_api.ts
  shared/community/admin/admin_mapper.ts
  shared/community/comments/comment_mapper.ts
  shared/community/comments/comments.ts
  shared/community/likes/likes.ts
  shared/community/likes/likes_mapper.ts
  shared/community/oauth/oauth_mapper.ts
  shared/community/oauth/oauths.ts
  shared/community/posts/post_mapper.ts
  shared/community/posts/posts.ts
  shared/community/rbac.ts
  shared/community/users/users.ts
  shared/index.ts
  shared/posts/enums.ts
Labels: type

#216 [FE] 라이트모드 스타일 임시 제거 및 클라이언트에 watch 스크립트 추가
  client/package.json
  client/src/index.css
  client/vite.config.ts
Labels: front-end

#218 ✨ [feat] : docker-compose -> 프로젝트 별 이미지 빌드 및 실행 환경
  chat_server/Dockerfile
  chat_server/app.ts
  chat_server/events/message_events.ts
  chat_server/index.ts
  chat_server/package.json
  consumer-server/Dockerfile
  docker-compose-kafka.yaml
  docker-compose-server.yaml
  server/Dockerfile
Labels: docker

#221 [BE] 회원가입 로그인 API 마이그레이션
  nestjs-migration/package.json
  nestjs-migration/src/app.module.ts
  nestjs-migration/src/auth/auth.module.ts
  nestjs-migration/src/auth/auth.service.spec.ts
  nestjs-migration/src/auth/auth.service.ts
  nestjs-migration/src/config/db.config.ts
  nestjs-migration/src/user/constant/user.constants.ts
  nestjs-migration/src/user/dto/login.dto.ts
  nestjs-migration/src/user/entities/user.entity.ts
  nestjs-migration/src/user/user.controller.spec.ts
  nestjs-migration/src/user/user.controller.ts
  nestjs-migration/src/user/user.entity.ts
  nestjs-migration/src/user/user.module.ts
  nestjs-migration/src/user/user.repository.ts
  nestjs-migration/src/user/user.service.spec.ts
  nestjs-migration/src/user/user.service.ts
  nestjs-migration/src/utils/crypto.util.ts
  nestjs-migration/src/utils/date.util.ts
Labels: back-end

#217 [BE] nestjs 초기 설정
  nestjs-migration/.eslintrc.js
  nestjs-migration/.gitignore
  nestjs-migration/README.md
  nestjs-migration/nest-cli.json
  nestjs-migration/package.json
  nestjs-migration/src/app.controller.spec.ts
  nestjs-migration/src/app.controller.ts
  nestjs-migration/src/app.module.ts
  nestjs-migration/src/app.service.ts
  nestjs-migration/src/auth/auth.module.ts
  nestjs-migration/src/auth/auth.service.spec.ts
  nestjs-migration/src/auth/auth.service.ts
  nestjs-migration/src/common/exceptions/server-error.exception.ts
  nestjs-migration/src/common/filters/global-exception.filter.ts
  nestjs-migration/src/config/app.config.ts
  nestjs-migration/src/config/auth.config.ts
  nestjs-migration/src/config/db.config.ts
  nestjs-migration/src/config/jwt.config.ts
  nestjs-migration/src/db/db.module.ts
  nestjs-migration/src/db/db.service.ts
  nestjs-migration/src/main.ts
  nestjs-migration/src/user/constant/user.constants.ts
  nestjs-migration/src/user/dto/create-user.dto.ts
  nestjs-migration/src/user/dto/login.dto.ts
  nestjs-migration/src/user/entities/user.entity.ts
  nestjs-migration/src/user/user.controller.spec.ts
  nestjs-migration/src/user/user.controller.ts
  nestjs-migration/src/user/user.module.ts
  nestjs-migration/src/user/user.repository.ts
  nestjs-migration/src/user/user.service.spec.ts
  nestjs-migration/src/user/user.service.ts
  nestjs-migration/src/utils/crypto.util.ts
  nestjs-migration/src/utils/date.util.ts
  nestjs-migration/test/app.e2e-spec.ts
  nestjs-migration/test/jest-e2e.json
  nestjs-migration/tsconfig.build.json
  nestjs-migration/tsconfig.json
  package.json
Labels: back-end, database

#234 [BE] 인증 미들웨어 마이그레이션
  nestjs-migration/package.json
  nestjs-migration/src/app.module.ts
  nestjs-migration/src/auth/auth.module.ts
  nestjs-migration/src/auth/auth.service.spec.ts
  nestjs-migration/src/auth/auth.service.ts
  nestjs-migration/src/auth/constants/auth.constants.ts
  nestjs-migration/src/auth/entity/refresh-tokens.entity.ts
  nestjs-migration/src/auth/refresh-tokens.repository.ts
  nestjs-migration/src/common/guard/constants/guard.constants.ts
  nestjs-migration/src/common/guard/login.guard.ts
  nestjs-migration/src/common/guard/token.guard.ts
  nestjs-migration/src/user/user.controller.ts
  nestjs-migration/src/user/user.module.ts
  nestjs-migration/src/user/user.service.spec.ts
  nestjs-migration/src/user/user.service.ts
Labels: back-end

#236 ✨ [feat] DOCKER + NGINX 통합 배포
  chat_server/Dockerfile
  chat_server/app.ts
  chat_server/index.ts
  chat_server/utils/api.ts
  client/Dockerfile
  client/vite.config.ts
  consumer-server/Dockerfile
  consumer-server/src/config/dbConfig.ts
  consumer-server/src/index.ts
  docker-command.sh
  docker-compose-server.yaml
  nginx/default.conf
  nginx/nginx.conf
  server/Dockerfile
  server/app.ts
  server/db/connect.ts
  server/utils/token.ts
  shared/package.json
Labels: docker, nginx

#242 🐛 [fix] : role_permission 테이블 생성 안되는 오류 수정
  sql/09_role_permission.sql
Labels: bug, database

#240 [BE] 로그아웃, 비밀번호 재확인 API 마이그레이션
  nestjs-migration/src/user/constant/user.constants.ts
  nestjs-migration/src/user/dto/check-password.dto.ts
  nestjs-migration/src/user/user.controller.spec.ts
  nestjs-migration/src/user/user.controller.ts
  nestjs-migration/src/user/user.service.spec.ts
  nestjs-migration/src/user/user.service.ts
Labels: back-end

#248 [BE] 게시물 API 마이그레이션
  nestjs-migration/src/app.module.ts
  nestjs-migration/src/like/entities/like.entity.ts
  nestjs-migration/src/like/like.controller.spec.ts
  nestjs-migration/src/like/like.controller.ts
  nestjs-migration/src/like/like.module.ts
  nestjs-migration/src/like/like.service.spec.ts
  nestjs-migration/src/like/like.service.ts
  nestjs-migration/src/log/dto/add-user-log.dto.ts
  nestjs-migration/src/log/dto/get-log.dto.ts
  nestjs-migration/src/log/entity/log.entity.ts
  nestjs-migration/src/log/log.module.ts
  nestjs-migration/src/log/log.repository.ts
  nestjs-migration/src/log/log.service.spec.ts
  nestjs-migration/src/log/log.service.ts
  nestjs-migration/src/post/constant/post.constants.ts
  nestjs-migration/src/post/dto/create-post.dto.ts
  nestjs-migration/src/post/dto/get-post-headers.dto.ts
  nestjs-migration/src/post/dto/read-posts-query.dto.ts
  nestjs-migration/src/post/dto/update-post.dto.ts
  nestjs-migration/src/post/entities/post.entity.ts
  nestjs-migration/src/post/post.controller.spec.ts
  nestjs-migration/src/post/post.controller.ts
  nestjs-migration/src/post/post.module.ts
  nestjs-migration/src/post/post.repository.spec.ts
  nestjs-migration/src/post/post.repository.ts
  nestjs-migration/src/post/post.service.spec.ts
  nestjs-migration/src/post/post.service.ts
  nestjs-migration/src/user/entities/user.entity.ts
  nestjs-migration/src/user/user.module.ts
  nestjs-migration/src/utils/bad-word-regex/README.md
  nestjs-migration/src/utils/bad-word-regex/constants.ts
  nestjs-migration/src/utils/bad-word-regex/fillRegexs.ts
  nestjs-migration/src/utils/bad-word-regex/regexTask.ts
  nestjs-migration/src/utils/bad-word-regex/regexs.json
  nestjs-migration/src/utils/bad-word-regex/testCase.ts
  nestjs-migration/src/utils/text-formatter.ts
  nestjs-migration/src/utils/user-logs-utils.ts
  nestjs-migration/tsconfig.json
Labels: back-end

#232 [FE] 소셜 로그인 재확인
  client/src/api/users/oauth.ts
  client/src/component/User/OAuthLoginButtons.tsx
  client/src/component/User/css/OAuthLoginButtons.css.ts
  client/src/page/OAuthRedirectHandler.tsx
  client/src/page/User/CheckPassword.css.ts
  client/src/page/User/CheckPassword.tsx
  client/src/page/User/Login.css.ts
  client/src/page/User/Login.tsx
  client/src/page/User/ProfileUpdate.css.ts
  shared/community/oauth/oauths.ts
Labels: front-end

#233 [FE] 소셜 로그인 연동 추가/해제
  client/src/App.tsx
  client/src/api/users/crud.ts
  client/src/api/users/oauth.ts
  client/src/component/Header/DropdownMenu.tsx
  client/src/component/User/OAuthLoginButtons.tsx
  client/src/component/User/css/OAuthLoginButtons.css.ts
  client/src/page/OAuth/OAuthLink.css.ts
  client/src/page/OAuth/OAuthLink.tsx
  client/src/page/OAuth/OAuthRedirectHandler.tsx
  shared/community/users/users.ts
  shared/community/users/users_mapper.ts
  shared/index.ts
Labels: front-end

#245 [BE] RBAC 관련 기능 추가 및 마이그레이션
  nestjs-migration/package.json
  nestjs-migration/src/app.module.ts
  nestjs-migration/src/auth/auth.service.spec.ts
  nestjs-migration/src/auth/auth.service.ts
  nestjs-migration/src/auth/interfaces/token.interface.ts
  nestjs-migration/src/common/decorator/rbac.decorator.ts
  nestjs-migration/src/common/decorator/user.decorator.ts
  nestjs-migration/src/common/guard/login.guard.ts
  nestjs-migration/src/common/guard/rbac.guard.ts
  nestjs-migration/src/common/guard/token.guard.ts
  nestjs-migration/src/common/interface/user-entity.interface.ts
  nestjs-migration/src/config/oauth.config.ts
  nestjs-migration/src/oauth/__snapshots__/oauth.service.spec.ts.snap
  nestjs-migration/src/oauth/config/oauth-props.config.ts
  nestjs-migration/src/oauth/constants/oauth.constants.ts
  nestjs-migration/src/oauth/dto/provider-param.dto.ts
  nestjs-migration/src/oauth/interfaces/oauth.interface.ts
  nestjs-migration/src/oauth/oauth.controller.spec.ts
  nestjs-migration/src/oauth/oauth.controller.ts
  nestjs-migration/src/oauth/oauth.module.ts
  nestjs-migration/src/oauth/oauth.service.spec.ts
  nestjs-migration/src/oauth/oauth.service.ts
  nestjs-migration/src/rbac/constants/rbac.constants.ts
  nestjs-migration/src/rbac/entities/permissions.entity.ts
  nestjs-migration/src/rbac/entities/role-permission.entity.ts
  nestjs-migration/src/rbac/entities/roles.entity.ts
  nestjs-migration/src/rbac/rbac.module.ts
  nestjs-migration/src/rbac/rbac.service.spec.ts
  nestjs-migration/src/rbac/rbac.service.ts
  nestjs-migration/src/rbac/repositories/permissions.repository.ts
  nestjs-migration/src/rbac/repositories/role-permission.repository.ts
  nestjs-migration/src/rbac/repositories/roles.repository.ts
  nestjs-migration/src/user/entities/user.entity.ts
  nestjs-migration/src/user/user.controller.spec.ts
  nestjs-migration/src/user/user.controller.ts
  nestjs-migration/src/user/user.module.ts
  nestjs-migration/src/user/user.service.ts
  shared/package.json
  shared/tsconfig.json
  sql/08_permissions.sql
Labels: back-end

#250 ✨ [feat] 채팅 페이지 -> aside로 바꾸기
  client/src/App.css.ts
  client/src/App.tsx
  client/src/component/Chats/ChatAside/ChatAside.tsx
  client/src/component/Chats/ChatRoom/ChatInput.tsx
  client/src/component/Chats/ChatRoom/ChatRoom.css.ts
  client/src/component/Chats/ChatRoom/ChatRoom.tsx
  client/src/component/Chats/ChatRoom/MyChat.tsx
  client/src/component/Chats/ChatRoom/YourChat.tsx
  client/src/component/Chats/ChatRooms/ChatHeader.tsx
  client/src/component/Chats/ChatRooms/ChatRooms.css.ts
  client/src/component/Chats/ChatRooms/ChatRooms.tsx
  client/src/component/Chats/ChatRooms/MyChatRooms.tsx
  client/src/component/Chats/ChatRooms/Rooms/Room.tsx
  client/src/component/Chats/ChatRooms/Rooms/Rooms.css.ts
  client/src/component/Chats/ChatRooms/SearchedChatRooms.tsx
  client/src/component/Header/Header.css.ts
  client/src/component/Header/Header.tsx
  client/src/component/Posts/PostInfo.css.ts
  client/src/component/common/Loader/Loader.css.ts
  client/src/page/Chat/ChatTestPage.tsx
  client/src/state/ChatAsideStore.ts
Labels: front-end

#249 [BE] 소셜 로그인 처리 API 마이그레이션
  nestjs-migration/package.json
  nestjs-migration/src/app.module.ts
  nestjs-migration/src/main.ts
  nestjs-migration/src/oauth/constants/oauth-token-service.constatns.ts
  nestjs-migration/src/oauth/dto/oauth-login.dto.ts
  nestjs-migration/src/oauth/entities/oauth-connection.entity.ts
  nestjs-migration/src/oauth/entities/oauth-provider.entity.ts
  nestjs-migration/src/oauth/oauth.controller.spec.ts
  nestjs-migration/src/oauth/oauth.controller.ts
  nestjs-migration/src/oauth/oauth.module.ts
  nestjs-migration/src/oauth/oauth.service.spec.ts
  nestjs-migration/src/oauth/oauth.service.ts
  nestjs-migration/src/oauth/oauthtoken.service.spec.ts
  nestjs-migration/src/oauth/oauthtoken.service.ts
  nestjs-migration/src/oauth/repositories/oauth-connection.repository.ts
  nestjs-migration/src/oauth/repositories/oauth-provider.repository.ts
  nestjs-migration/src/user/user.repository.ts
  nestjs-migration/src/utils/oauth.util.ts
Labels: back-end

#251 [BE] 소셜 로그인 재확인 마이그레이션
  nestjs-migration/src/oauth/oauth.controller.spec.ts
  nestjs-migration/src/oauth/oauth.controller.ts
  nestjs-migration/src/oauth/oauth.service.spec.ts
  nestjs-migration/src/oauth/oauth.service.ts
Labels: back-end

#256 [Fix / Style / Feat] 채팅 aside 스타일 및 문제 수정
  client/src/App.tsx
  client/src/component/Chats/ChatAside/ChatAside.css.ts
  client/src/component/Chats/ChatAside/ChatAside.tsx
  client/src/component/Chats/ChatBtn/ChatBtn.css.ts
  client/src/component/Chats/ChatBtn/ChatBtn.tsx
  client/src/component/Chats/ChatRoom/ChatRoom.css.ts
  client/src/component/Chats/ChatRoom/ChatRoomHeader.tsx
  client/src/component/Chats/ChatRooms/ChatFooter.tsx
  client/src/component/Chats/ChatRooms/ChatHeader.tsx
  client/src/component/Chats/ChatRooms/ChatRooms.css.ts
  client/src/component/Chats/ChatRooms/ChatRooms.tsx
  client/src/component/Chats/ChatRooms/MyChatRooms.tsx
  client/src/component/Chats/ChatRooms/Rooms/Room.tsx
  client/src/component/Chats/ChatRooms/SearchedChatRooms.tsx
  client/src/page/Chat/ChatPage.css.ts
  client/src/page/Chat/ChatPage.tsx
Labels: front-end

#252 [BE] 소셜 로그인 연동 추가 및 해제 마이그레이션
  nestjs-migration/src/oauth/oauth.controller.spec.ts
  nestjs-migration/src/oauth/oauth.controller.ts
  nestjs-migration/src/oauth/oauth.service.spec.ts
  nestjs-migration/src/oauth/oauth.service.ts
  nestjs-migration/src/oauth/oauthtoken.service.spec.ts
  nestjs-migration/src/oauth/oauthtoken.service.ts
  nestjs-migration/src/oauth/repositories/oauth-connection.repository.ts
  nestjs-migration/src/utils/oauth.util.ts
Labels: back-end

#255 [BE] 게시물 API 마이그레이션 수정
  nestjs-migration/src/post/dto/delete-post.dto.ts
  nestjs-migration/src/post/dto/get-post-headers.dto.ts
  nestjs-migration/src/post/dto/update-post.dto.ts
  nestjs-migration/src/post/entities/post.entity.ts
  nestjs-migration/src/post/post.controller.spec.ts
  nestjs-migration/src/post/post.controller.ts
  nestjs-migration/src/post/post.module.ts
  nestjs-migration/src/post/post.repository.ts
  nestjs-migration/src/post/post.service.spec.ts
  nestjs-migration/src/post/post.service.ts
Labels: bug, back-end

#257 [BE] 댓글 API 마이그레이션
  nestjs-migration/src/app.module.ts
  nestjs-migration/src/comment/comment.controller.spec.ts
  nestjs-migration/src/comment/comment.controller.ts
  nestjs-migration/src/comment/comment.module.ts
  nestjs-migration/src/comment/comment.repository.ts
  nestjs-migration/src/comment/comment.service.spec.ts
  nestjs-migration/src/comment/comment.service.ts
  nestjs-migration/src/comment/constant/comment-constants.ts
  nestjs-migration/src/comment/dto/create-comment.dto.ts
  nestjs-migration/src/comment/dto/delete-comment.dto.ts
  nestjs-migration/src/comment/dto/read-comment.dto.ts
  nestjs-migration/src/comment/dto/update-comment.dto.ts
  nestjs-migration/src/comment/entities/comment-likes.entity.ts
  nestjs-migration/src/comment/entities/comment.entity.ts
  nestjs-migration/src/like/entities/like.entity.ts
  nestjs-migration/src/log/entities/log.entity.ts
  nestjs-migration/src/log/log.repository.ts
  nestjs-migration/src/post/entities/post.entity.ts
  nestjs-migration/src/post/post.module.ts
  nestjs-migration/src/post/post.service.ts
  nestjs-migration/src/user/entities/user.entity.ts
Labels: back-end

#260 [FE] 버튼, 텍스트 입력 컴포넌트 기능 작성
  client/src/App.tsx
  client/src/component/Header/Header.tsx
  client/src/component/common/Button.temp.css.ts
  client/src/component/common/Button.tsx
  client/src/component/common/TextInput.temp.css.ts
  client/src/component/common/TextInput.tsx
  client/src/component/common/Textarea.temp.css.ts
  client/src/component/common/Textarea.tsx
  client/src/page/UITest.tsx
  client/src/utils/detectMode.ts
  client/vite.config.ts
Labels: front-end

#261 [BE] 유저 API 마이그레이션 마무리
  nestjs-migration/src/auth/auth.service.ts
  nestjs-migration/src/common/decorator/required-password.decorator.ts
  nestjs-migration/src/common/guard/password.guard.ts
  nestjs-migration/src/oauth/oauth.module.ts
  nestjs-migration/src/oauth/oauth.service.ts
  nestjs-migration/src/oauth/repositories/oauth-connection.repository.ts
  nestjs-migration/src/user/constant/user.constants.ts
  nestjs-migration/src/user/dto/update-user.dto.ts
  nestjs-migration/src/user/user.controller.spec.ts
  nestjs-migration/src/user/user.controller.ts
  nestjs-migration/src/user/user.module.ts
  nestjs-migration/src/user/user.repository.ts
  nestjs-migration/src/user/user.service.spec.ts
  nestjs-migration/src/user/user.service.ts
Labels: back-end

#270 [FE] 전체적인 UI 수정
  .prettierrc.json
  client/postcss.config.cjs
  client/src/App.tsx
  client/src/component/Comments/CommentForm/CommentForm.tsx
  client/src/component/Comments/CommentItem/CommentItem.tsx
  client/src/component/Comments/CommentLikeButton/CommentLikeButton.tsx
  client/src/component/Comments/Comments.tsx
  client/src/component/Header/DropdownMenu.tsx
  client/src/component/Header/Header.tsx
  client/src/component/Posts/PostInfo.tsx
  client/src/component/Posts/PostList/MainPostList.tsx
  client/src/component/Posts/PostList/PostList.tsx
  client/src/component/Posts/Rank/UserRank.tsx
  client/src/component/User/DuplicationCheckButton.tsx
  client/src/component/User/InputField.tsx
  client/src/component/User/InputForm.tsx
  client/src/component/User/SubmitButton.tsx
  client/src/component/common/Button.tsx
  client/src/component/common/Pagination/Pagination.tsx
  client/src/component/common/SearchForm/SearchForm.tsx
  client/src/component/common/TextInput.tsx
  client/src/component/common/Textarea.tsx
  client/src/index.css
  client/src/page/Category/Community.tsx
  client/src/page/Main/Main.css.ts
  client/src/page/Main/Main.tsx
  client/src/page/Posts/PostInfoPage.tsx
  client/src/page/User/Join.tsx
  client/src/page/User/Login.tsx
  client/tailwind.config.js
  package.json
Labels: front-end

#271 [BE] 통계 API 마이그레이션
  nestjs-migration/src/admin/admin.controller.spec.ts
  nestjs-migration/src/admin/admin.controller.ts
  nestjs-migration/src/admin/admin.module.ts
  nestjs-migration/src/admin/admin.service.spec.ts
  nestjs-migration/src/admin/admin.service.ts
  nestjs-migration/src/admin/dto/get-stats.dto.ts
  nestjs-migration/src/comment/comment.module.ts
  nestjs-migration/src/comment/comment.repository.ts
  nestjs-migration/src/common/guard/token.guard.ts
  nestjs-migration/src/log/constants/log.constants.ts
  nestjs-migration/src/log/dto/get-log-query.dto.ts
  nestjs-migration/src/log/dto/get-log.dto.ts
  nestjs-migration/src/log/entities/log-category.entity.ts
  nestjs-migration/src/log/entities/log.entity.ts
  nestjs-migration/src/log/log.module.ts
  nestjs-migration/src/log/log.repository.ts
  nestjs-migration/src/log/log.service.spec.ts
  nestjs-migration/src/log/log.service.ts
  nestjs-migration/src/post/post.repository.ts
  nestjs-migration/src/user/user.repository.ts
Labels: back-end

#262 [BE] 사용자 관리 API 마이그레이션
  nestjs-migration/src/admin/admin.controller.spec.ts
  nestjs-migration/src/admin/admin.controller.ts
  nestjs-migration/src/admin/admin.module.ts
  nestjs-migration/src/admin/admin.service.spec.ts
  nestjs-migration/src/admin/admin.service.ts
  nestjs-migration/src/admin/dto/get-posts.dto.ts
  nestjs-migration/src/admin/dto/get-stats.dto.ts
  nestjs-migration/src/admin/dto/get-users.dto.ts
  nestjs-migration/src/app.module.ts
  nestjs-migration/src/comment/comment.module.ts
  nestjs-migration/src/comment/comment.repository.ts
  nestjs-migration/src/common/guard/rbac.guard.ts
  nestjs-migration/src/common/guard/token.guard.ts
  nestjs-migration/src/log/constants/log.constants.ts
  nestjs-migration/src/log/dto/get-log-query.dto.ts
  nestjs-migration/src/log/dto/get-log.dto.ts
  nestjs-migration/src/log/entities/log-category.entity.ts
  nestjs-migration/src/log/entities/log.entity.ts
  nestjs-migration/src/log/log.module.ts
  nestjs-migration/src/log/log.repository.ts
  nestjs-migration/src/log/log.service.spec.ts
  nestjs-migration/src/log/log.service.ts
  nestjs-migration/src/post/post.repository.ts
  nestjs-migration/src/user/user.repository.ts
  nestjs-migration/src/user/user.service.ts
Labels: back-end

#264 [BE] 채팅 메시지 컨슈머 장애 처리
  consumer-server/package.json
  consumer-server/src/config/db.config.ts
  consumer-server/src/config/dbConfig.ts
  consumer-server/src/config/index.ts
  consumer-server/src/config/kafka.config.ts
  consumer-server/src/config/kafkaConfig.ts
  consumer-server/src/index.ts
  consumer-server/src/kafka/index.ts
  consumer-server/src/models/chat.model.ts
  consumer-server/src/models/index.ts
  consumer-server/src/services/chat.service.ts
  consumer-server/src/services/kafkaService.ts
  consumer-server/tsconfig.json
  consumer-server/types/index.d.ts
  package.json
Labels: enhancement, back-end

#275 [FE] 다크모드/라이트모드 추가
  client/src/component/Comments/CommentForm/CommentForm.tsx
  client/src/component/Comments/CommentLikeButton/CommentLikeButton.tsx
  client/src/component/Comments/Comments.tsx
  client/src/component/Header/DropdownMenu.tsx
  client/src/component/Header/Header.tsx
  client/src/component/Posts/Modal/DeleteModal.css.ts
  client/src/component/Posts/Modal/PostModal.css.ts
  client/src/component/Posts/PostInfo.tsx
  client/src/component/Posts/PostList/MainPostList.tsx
  client/src/component/Posts/PostList/PostList.tsx
  client/src/component/Posts/Rank/UserRank.tsx
  client/src/component/User/DuplicationCheckButton.tsx
  client/src/component/User/InputField.tsx
  client/src/component/common/Button.tsx
  client/src/component/common/Pagination/Pagination.tsx
  client/src/component/common/SearchForm/SearchForm.tsx
  client/src/component/common/Textarea.tsx
  client/src/index.css
  client/src/page/Category/Community.tsx
  client/src/page/Main/Main.tsx
  client/src/page/User/Join.tsx
  client/src/page/User/Login.tsx
  client/src/state/ThemeStore.ts
  client/tailwind.config.js
Labels: front-end

#272 [BE] 채팅방 API 마이그레이션
  nestjs-migration/src/app.module.ts
  nestjs-migration/src/chat/chat.controller.spec.ts
  nestjs-migration/src/chat/chat.controller.ts
  nestjs-migration/src/chat/chat.module.ts
  nestjs-migration/src/chat/chat.service.spec.ts
  nestjs-migration/src/chat/chat.service.ts
  nestjs-migration/src/chat/dto/chat-result.dto.ts
  nestjs-migration/src/chat/dto/create-room.dto.ts
  nestjs-migration/src/chat/dto/enter-room.dto.ts
  nestjs-migration/src/chat/dto/join-room.dto.ts
  nestjs-migration/src/chat/dto/leave-room.dto.ts
  nestjs-migration/src/chat/dto/message.dto.ts
  nestjs-migration/src/chat/dto/read-room-query.dto.ts
  nestjs-migration/src/chat/entities/member.entity.ts
  nestjs-migration/src/chat/entities/message.entity.ts
  nestjs-migration/src/chat/entities/room.entity.ts
  nestjs-migration/src/chat/repositories/chat.member.repository.ts
  nestjs-migration/src/chat/repositories/chat.messages.repository.ts
  nestjs-migration/src/chat/repositories/chat.room.repoistory.ts
  nestjs-migration/src/user/entities/user.entity.ts
Labels: back-end
