Repository programmers-kdt-full-stack-3rd/community-board, pull requests merged in 2024-10, with the labels that each got.

#276 [FE] 모달 컴포넌트 추출
  client/index.html
  client/src/App.css.ts
  client/src/App.tsx
  client/src/component/Chats/ChatRooms/Modal/CreateRoomModal.tsx
  client/src/component/Chats/ChatRooms/SearchedChatRooms.tsx
  client/src/component/Comments/CommentItem/CommentItem.tsx
  client/src/component/Comments/CommentLikeButton/CommentLikeButton.tsx
  client/src/component/Comments/Comments.tsx
  client/src/component/Header/DropdownMenu.tsx
  client/src/component/Header/Header.tsx
  client/src/component/Header/UserDeleteModal.css.ts
  client/src/component/Header/UserDeleteModal.tsx
  client/src/component/Posts/Modal/DeleteModal.css.ts
  client/src/component/Posts/Modal/DeleteModal.tsx
  client/src/component/Posts/Modal/PostModal.tsx
  client/src/component/Posts/PostInfo.tsx
  client/src/component/common/Button.tsx
  client/src/component/common/Modal/AlertModal.tsx
  client/src/component/common/Modal/ConfirmModal.tsx
  client/src/component/common/Modal/GlobalErrorModal.tsx
  client/src/component/common/Modal/Modal.tsx
  client/src/component/utils/ErrorModal.css.ts
  client/src/component/utils/ErrorModal.tsx
  client/src/page/Posts/PostInfoPage.tsx
  client/src/page/UITest.tsx
  client/src/page/User/CheckPassword.tsx
  client/src/root.css.ts
  client/src/state/GlobalErrorModalStore.ts
  client/src/state/errorModalStore.ts
Labels: front-end

#277 ✨ [feat] 게시글 편집기
  client/package.json
  client/src/App.tsx
  client/src/api/api.ts
  client/src/api/posts/crud.ts
  client/src/component/Posts/Editer/CustomEditor.tsx
  client/src/component/Posts/Modal/PostModal.css.ts
  client/src/component/Posts/PostInfo.tsx
  client/src/page/Category/Community.tsx
  client/src/page/Posts/UpsertPostPage.tsx
  server/controller/ image_controller.ts
  server/package.json
  server/route/image_router.ts
  server/route/route.ts
  server/utils/upload-image.ts
Labels: back-end, front-end

#278 [fix] App모듈에 삭제되었던 Admin 모듈 다시 등록
  nestjs-migration/src/app.module.ts
Labels: bug, back-end

#281 [FE] 어드민 페이지 수정
  client/src/App.tsx
  client/src/component/Admin/AdminSidebar.css.ts
  client/src/component/Admin/AdminSidebar.tsx
  client/src/component/Admin/PostMgmt/PostMgmt.tsx
  client/src/component/Admin/Stats/AdminGraph.tsx
  client/src/component/Admin/Stats/ChartData.ts
  client/src/component/Admin/UserMgmt/UserList.tsx
  client/src/component/Header/DropdownMenu.tsx
  client/src/hook/useScrollCount.ts
  client/src/page/Admin/AdminPage.tsx
  client/src/page/Admin/AdminPostMgmtPage.tsx
  client/src/page/Admin/AdminStatsPage.tsx
  client/src/page/Admin/AdminUserLogPage.tsx
  client/src/page/Admin/AdminUserMgmtPage.tsx
  client/src/page/OAuth/OAuthLink.tsx
  client/src/page/User/CheckPassword.tsx
  client/src/state/ThemeStore.ts
Labels: front-end

#284 [BE] 마이그레이션 api 테스트
  .gitignore
  migration-test/jest.config.js
  migration-test/package.json
  migration-test/sql/01_roles.sql
  migration-test/sql/02_users.sql
  migration-test/sql/03_posts.sql
  migration-test/sql/04_comments.sql
  migration-test/sql/05_chats.sql
  migration-test/sql/06_refresh_tokens.sql
  migration-test/sql/07_oauth.sql
  migration-test/sql/08_permissions.sql
  migration-test/sql/09_role_permission.sql
  migration-test/sql/10_user_log_categories.sql
  migration-test/sql/11_user_logs.sql
  migration-test/sql/docker-compose.yaml
  migration-test/test/api.test.ts
  migration-test/test/config/env.config.ts
  migration-test/test/init/db-init-setup.ts
  migration-test/test/init/init-db.sql
  migration-test/test/interface/api-test-case.interface.ts
  migration-test/test/testCase/admin-api.testcase.ts
  migration-test/test/testCase/chat-api.testcase.ts
  migration-test/test/testCase/comment-api.testcase.ts
  migration-test/test/testCase/like-api.testcase.ts
  migration-test/test/testCase/post-api.testcase.ts
  migration-test/test/testCase/user-api.testcase.ts
  migration-test/tsconfig.build.json
  migration-test/tsconfig.json
  nestjs-migration/.gitignore
  nestjs-migration/package.json
  nestjs-migration/src/app.module.ts
  nestjs-migration/src/config/db.config.ts
  nestjs-migration/src/health-check/health.controller.ts
  nestjs-migration/src/health-check/health.module.ts
  nestjs-migration/src/main.ts
  package.json
  server/package.json
Labels: back-end

#286 [FE] 게시글 편집기 및 게시글 열람 페이지
  client/package.json
  client/src/component/Posts/Editer/CustomEditor.tsx
  client/src/component/Posts/Editer/ImageManager.tsx
  client/src/component/Posts/Editer/toolbarColors.ts
  client/src/component/Posts/PostInfo.tsx
  client/src/index.css
  client/src/page/Posts/UpsertPostPage.tsx
  client/src/style/quill-post-color.css
  client/src/style/quill-post.css
Labels: front-end

#293 [FE] 랭킹 페이지 구현
  client/src/App.tsx
  client/src/component/Admin/Stats/AdminGraph.tsx
  client/src/component/Admin/Stats/ChartData.ts
  client/src/component/Posts/PostList/MainPostList.tsx
  client/src/component/Posts/Rank/UserRank.tsx
  client/src/component/common/Confetti/Confetti.tsx
  client/src/page/Admin/AdminPage.tsx
  client/src/page/Rank/Rank.tsx
  client/tailwind.config.js
  package.json
Labels: front-end

#294 [FE/BE] | 마이 페이지 (프로필) 추가
  client/src/App.tsx
  client/src/api/users/crud.ts
  client/src/assets/icons/profile-icon.svg
  client/src/component/Header/DropdownMenu.tsx
  client/src/component/Header/Header.tsx
  client/src/component/Posts/Modal/PostModal.css.ts
  client/src/component/Profile/Modal/PasswordUpdateModal.tsx
  client/src/component/Profile/ProfileItem.tsx
  client/src/component/Profile/ProfileItemBody.tsx
  client/src/component/Profile/ProfileItemHeader.tsx
  client/src/component/common/TextInput.tsx
  client/src/page/OAuth/OAuthRedirectHandler.tsx
  client/src/page/Profile/ProfilePage.tsx
  client/src/page/User/Login.tsx
  client/src/state/store.ts
  server/controller/oauth_controller.ts
  server/controller/users_controller.ts
  server/db/context/users_context.ts
  server/route/users_router.ts
  server/utils/validations/users/constants.ts
  server/utils/validations/users/user.ts
  shared/community/users/users.ts
  shared/community/users/users_api.ts
  shared/community/users/users_mapper.ts
  shared/index.ts
  sql/02_users.sql
Labels: back-end, front-end

#295 [BE] 메인페이지 랭킹 추가
  nestjs-migration/src/app.module.ts
  nestjs-migration/src/comment/comment.repository.ts
  nestjs-migration/src/post/post.repository.ts
  nestjs-migration/src/rank/constant/rank.constants.ts
  nestjs-migration/src/rank/dto/get-top-activities.dto.ts
  nestjs-migration/src/rank/dto/get-top-comments.dto.ts
  nestjs-migration/src/rank/dto/get-top-posts.dto.ts
  nestjs-migration/src/rank/dto/rank-results.dto.ts
  nestjs-migration/src/rank/rank.controller.spec.ts
  nestjs-migration/src/rank/rank.controller.ts
  nestjs-migration/src/rank/rank.module.ts
  nestjs-migration/src/rank/rank.repository.ts
  nestjs-migration/src/rank/rank.service.spec.ts
  nestjs-migration/src/rank/rank.service.ts
  nestjs-migration/src/user/user.repository.ts
Labels: back-end

#288 [BE/DB] 게시글 카테고리 기능 추가
  nestjs-migration/src/post/constant/post.constants.ts
  nestjs-migration/src/post/dto/create-post.dto.ts
  nestjs-migration/src/post/dto/get-post-headers.dto.ts
  nestjs-migration/src/post/dto/get-post.dto.ts
  nestjs-migration/src/post/dto/read-posts-query.dto.ts
  nestjs-migration/src/post/entities/post.entity.ts
  nestjs-migration/src/post/entities/post_categories.entity.ts
  nestjs-migration/src/post/post.controller.spec.ts
  nestjs-migration/src/post/post.controller.ts
  nestjs-migration/src/post/post.repository.ts
  nestjs-migration/src/post/post.service.spec.ts
  nestjs-migration/src/post/post.service.ts
  sql/03_post_categories.sql
  sql/04_posts.sql
  sql/05_comments.sql
  sql/06_chats.sql
  sql/07_refresh_tokens.sql
  sql/08_oauth.sql
  sql/09_permissions.sql
  sql/10_role_permission.sql
  sql/11_user_log_categories.sql
  sql/12_user_logs.sql
Labels: back-end, database

#290 [FE] 게시글 편집기 이미지 리사이징 및 편집기 세부 기능 구현
  client/package.json
  client/src/component/Posts/Editer/CustomEditor.tsx
  client/src/component/Posts/Editer/ImageManager.tsx
  client/src/component/Posts/Editer/constants.ts
  client/src/index.css
  client/src/page/Posts/UpsertPostPage.tsx
  client/src/style/quill/colors.css
  client/src/style/quill/post.css
  client/src/style/quill/quill.css
  client/src/style/quill/toolbar.css
  client/src/utils/getImageDimensions.ts
  client/src/utils/sanitizePostContent.ts
Labels: front-end

#298 [DB] posts 테이블 CREATE 문 오류 해결
  sql/04_posts.sql
Labels: bug, schema, database

#297 [FE] 메인페이지 / 랭킹 게시판
  client/src/api/Rank/rank_crud.ts
  client/src/component/Header/Header.tsx
  client/src/component/Posts/Rank/UserRank.tsx
  client/src/page/Rank/Rank.tsx
Labels: front-end

#291 [BE] 소켓 서버 메시지 캐싱 구현
  chat_server/config/index.ts
  chat_server/config/kafka_config.ts
  chat_server/config/redis_config.ts
  chat_server/events/chatroom_events.ts
  chat_server/events/message_events.ts
  chat_server/index.ts
  chat_server/services/cache_service.ts
  chat_server/services/chat_service.ts
  chat_server/services/kafka_service.ts
  chat_server/services/redis_service.ts
  chat_server/utils/api.ts
  chat_server/utils/kafka.ts
  chat_server/utils/redis.ts
Labels: enhancement, back-end

#302 [FE] 게시글 카테고리 기능
  client/src/App.tsx
  client/src/api/posts/crud.ts
  client/src/component/Header/Header.tsx
  client/src/component/Posts/Editer/ImageManager.tsx
  client/src/component/Posts/PostInfo.tsx
  client/src/hook/useCategory.ts
  client/src/hook/useParsedSearchParams.ts
  client/src/hook/usePostList.ts
  client/src/page/Category/Community.tsx
  client/src/page/Main/Main.tsx
  client/src/page/Posts/UpsertPostPage.tsx
  shared/community/posts/post_mapper.ts
  shared/community/posts/posts.ts
Labels: front-end

#305 [FE/BE] Express API to NestJs migration
  client/Dockerfile
  client/src/api/users/crud.ts
  client/src/component/User/SubmitButton.tsx
  client/src/component/common/Button.tsx
  client/src/page/Profile/ProfilePage.tsx
  client/src/page/User/Join.tsx
  docker-compose-server.yaml
  nestjs-migration/Dockerfile
  nestjs-migration/package.json
  nestjs-migration/src/app.module.ts
  nestjs-migration/src/image/dto/upload-image.dto.ts
  nestjs-migration/src/image/image.controller.spec.ts
  nestjs-migration/src/image/image.controller.ts
  nestjs-migration/src/image/image.module.ts
  nestjs-migration/src/image/image.service.spec.ts
  nestjs-migration/src/image/image.service.ts
  nestjs-migration/src/main.ts
  nestjs-migration/src/user/constant/user.constants.ts
  nestjs-migration/src/user/entities/user.entity.ts
  nestjs-migration/src/user/user.controller.ts
  nestjs-migration/src/user/user.repository.ts
  nestjs-migration/src/user/user.service.ts
Labels: back-end, front-end

#308 [FE] 버그/이슈 게시판 생성 및 템플릿 추가
  client/src/component/Posts/Editer/CustomEditor.tsx
  client/src/component/Posts/Editer/constants.ts
  client/src/hook/useCategory.ts
  client/src/page/Posts/PostInfoPage.tsx
  client/src/page/Posts/UpsertPostPage.tsx
  server/controller/posts_controller.ts
  server/db/context/posts_context.ts
Labels: front-end

#312 [fix] : 랭킹 API 오류 및 카테고리 페이징 수정
  nestjs-migration/src/comment/comment.repository.ts
  nestjs-migration/src/post/post.repository.ts
Labels: bug, back-end

#314 [FE] 선착순 쿠폰 추가 / CSS 정리
  client/src/component/Admin/PostMgmt/PostMgmt.css.ts
  client/src/component/Admin/Stats/Stats.css.ts
  client/src/component/Admin/UserLog/UserLog.css.ts
  client/src/component/Admin/UserLog/UserLogItem.tsx
  client/src/component/Admin/UserMgmt/UserList.css.ts
  client/src/component/Comments/CommentForm/CommentForm.css.ts
  client/src/component/Comments/CommentForm/CommentForm.tsx
  client/src/component/Comments/CommentItem/CommentItem.css.ts
  client/src/component/Comments/CommentItem/CommentItem.tsx
  client/src/component/Comments/CommentLikeButton/CommentLikeButton.css.ts
  client/src/component/Comments/Comments.css.ts
  client/src/component/Coupon/coupon.tsx
  client/src/component/Header/DropdownMenu.css.ts
  client/src/component/Header/Header.css.ts
  client/src/component/Posts/Modal/PostModal.css.ts
  client/src/component/Posts/Modal/PostModal.tsx
  client/src/component/Posts/PostInfo.css.ts
  client/src/component/Posts/PostInfo.tsx
  client/src/component/Posts/PostList/PostList.css.ts
  client/src/component/Profile/Modal/PasswordUpdateModal.tsx
  client/src/component/User/ErrorMessageForm.tsx
  client/src/component/User/OAuthLoginButtons.tsx
  client/src/component/User/css/InputField.css.ts
  client/src/component/User/css/OAuthLoginButtons.css.ts
  client/src/component/User/css/SubmitButton.css.ts
  client/src/component/User/css/errorMessage.css.ts
  client/src/component/common/Button.temp.css.ts
  client/src/component/common/Confetti/Confetti.tsx
  client/src/component/common/Loader/Loader.css.ts
  client/src/component/common/Loader/Loader.tsx
  client/src/component/common/Pagination/Pagination.css.ts
  client/src/component/common/SearchForm/SearchForm.css.ts
  client/src/component/common/TextInput.temp.css.ts
  client/src/component/common/Textarea.temp.css.ts
  client/src/page/Admin/AdminUserMgmtPage.css.ts
  client/src/page/Category/Community.tsx
  client/src/page/Main/Main.css.ts
  client/src/page/Main/Main.tsx
  client/src/page/OAuth/OAuthLink.css.ts
  client/src/page/Posts/PostInfoPage.css.ts
  client/src/page/Profile/ProfilePage.tsx
  client/src/page/Rank/Rank.tsx
  client/src/page/User/CheckPassword.css.ts
  client/src/page/User/EmailRegistration.tsx
  client/src/page/User/Join.css.ts
  client/src/page/User/Login.css.ts
  client/src/page/User/ProfileUpdate.css.ts
  client/src/page/User/ProfileUpdate.tsx
  client/src/page/error/NotFound.css.ts
  client/src/page/error/NotFound.tsx
  client/tailwind.config.js
Labels: front-end

#309 [FE] Q&A 게시판 구현
  client/src/App.tsx
  client/src/api/posts/crud.ts
  client/src/component/Comments/CommentItem/CommentItem.tsx
  client/src/component/Comments/Comments.tsx
  client/src/component/Header/DropdownMenu.tsx
  client/src/component/Header/Header.tsx
  client/src/component/Posts/PostInfo.tsx
  client/src/component/Posts/PostList/MainPostList.tsx
  client/src/component/Posts/PostList/PostList.tsx
  client/src/hook/useCategory.ts
  client/src/hook/usePostList.ts
  client/src/page/Category/Community.tsx
  client/src/page/Main/Main.tsx
  client/src/page/Posts/PostInfoPage.tsx
  client/src/state/PostInfoStore.ts
Labels: front-end

#315 [FE/BE] 채팅방 사이드바 + 팀원 모집 기능
  chat_server/services/chat_service.ts
  client/src/api/chats/crud.ts
  client/src/component/Chats/ChatAside/ChatAside.css.ts
  client/src/component/Chats/ChatRoom/ChatRoom.css.ts
  client/src/component/Chats/ChatRoom/ChatRoom.tsx
  client/src/component/Chats/ChatRoom/ChatRoomHeader.tsx
  client/src/component/Chats/ChatRoom/SideBar/ChatRoomSideBar.tsx
  client/src/component/Posts/PostInfo.tsx
  client/src/page/Category/Community.tsx
  client/src/page/Chat/ChatPage.css.ts
  client/src/page/Posts/UpsertPostPage.tsx
  nestjs-migration/src/chat/chat.controller.ts
  nestjs-migration/src/chat/chat.service.ts
  nestjs-migration/src/chat/constant/chat.constants.ts
  nestjs-migration/src/chat/dto/read-room-query.dto.ts
  nestjs-migration/src/chat/entities/room.entity.ts
  nestjs-migration/src/chat/repositories/chat.member.repository.ts
  nestjs-migration/src/chat/repositories/chat.room.repoistory.ts
  nestjs-migration/src/post/dto/create-post.dto.ts
  nestjs-migration/src/post/dto/get-post.dto.ts
  nestjs-migration/src/post/entities/post.entity.ts
  nestjs-migration/src/post/entities/recruting_posts.entity.ts
  nestjs-migration/src/post/post.module.ts
  nestjs-migration/src/post/post.repository.ts
  nestjs-migration/src/post/post.service.ts
  nestjs-migration/src/utils/boolean_map.ts
  shared/chat/chat_mapper.ts
  shared/chat/chats.ts
  shared/community/posts/post_mapper.ts
  shared/community/posts/posts.ts
  sql/13_recruting_posts.sql
Labels: back-end, front-end

#320 [BE] Q&A 게시판 댓글 채택 기능 추가
  .gitignore
  nestjs-migration/src/app.module.ts
  nestjs-migration/src/qna/dto/create-qna.dto.ts
  nestjs-migration/src/qna/dto/get-qna.dto.ts
  nestjs-migration/src/qna/entities/qna.entity.ts
  nestjs-migration/src/qna/qna.controller.spec.ts
  nestjs-migration/src/qna/qna.controller.ts
  nestjs-migration/src/qna/qna.module.ts
  nestjs-migration/src/qna/qna.repository.ts
  nestjs-migration/src/qna/qna.service.ts
  sql/06_qna.sql
  sql/07_chats.sql
  sql/10_refresh_tokens.sql
  sql/11_role_permission.sql
  sql/12_user_log_categories.sql
  sql/13_user_logs.sql
Labels: enhancement, back-end, database

#319 [BE] 선착순 이벤트 API
  client/src/api/coupon/coupon_crud.ts
  client/src/component/Coupon/coupon.tsx
  client/src/component/Header/DropdownMenu.tsx
  client/src/page/Profile/ProfilePage.tsx
  nestjs-migration/package.json
  nestjs-migration/src/app.controller.ts
  nestjs-migration/src/app.module.ts
  nestjs-migration/src/app.service.ts
  nestjs-migration/src/config/redis.config.ts
  nestjs-migration/src/coupon/constant/coupon.constants.ts
  nestjs-migration/src/coupon/coupon.consumer.ts
  nestjs-migration/src/coupon/coupon.controller.ts
  nestjs-migration/src/coupon/coupon.e2e.spec.ts
  nestjs-migration/src/coupon/coupon.module.ts
  nestjs-migration/src/coupon/coupon.service.ts
  nestjs-migration/src/coupon/entities/coupon.entity.ts
  nestjs-migration/src/coupon/entities/coupon_log.entity.ts
  nestjs-migration/src/coupon/repositories/coupon.repository.ts
  nestjs-migration/src/coupon/repositories/coupon_log.repository.ts
  nestjs-migration/src/main.ts
  nestjs-migration/src/redis/redis.controller.ts
  nestjs-migration/src/redis/redis.module.ts
  nestjs-migration/src/redis/redis.repository.ts
  nestjs-migration/src/redis/redis.service.ts
  nestjs-migration/src/user/entities/user.entity.ts
  package.json
  sql/13_coupons.sql
Labels: back-end

#321 [FE] Q&A 게시판 API 호출 구현
  client/src/api/posts/qna_crud.ts
  client/src/component/Comments/CommentItem/CommentItem.tsx
  client/src/component/Comments/Comments.tsx
  client/src/component/Posts/Editer/ImageManager.tsx
  client/src/component/Posts/PostList/EmptyPostListBody.tsx
  client/src/component/Posts/PostList/PostList.tsx
  client/src/hook/usePostList.ts
  client/src/page/error/NotFound.tsx
  client/src/state/PostInfoStore.ts
  client/src/style/quill/quill.css
  client/src/style/quill/toolbar.css
Labels: bug, front-end

#323 🐛 [fix] : 게시글 조회시 조회수 증가하도록 수정
  nestjs-migration/src/post/post.service.ts
Labels: bug, back-end

#324 [BE] 템플릿 검사 기능 추가
  client/src/state/GlobalErrorModalStore.ts
  nestjs-migration/src/post/constant/post.constants.ts
  nestjs-migration/src/post/post.service.ts
Labels: bug, back-end, front-end

#326 [FE] 교체하지 못하고 미뤄 두었던 곳에 기본 UI 컴포넌트 적용
  client/package.json
  client/src/App.tsx
  client/src/component/Header/Header.tsx
  client/src/component/Posts/Editer/ImageManager.tsx
  client/src/component/User/DuplicationCheckButton.tsx
  client/src/component/User/EmailForm.tsx
  client/src/component/User/InputField.tsx
  client/src/component/User/InputForm.tsx
  client/src/component/User/NicknameForm.tsx
  client/src/component/User/OAuthLoginButtons.tsx
  client/src/component/User/PasswordForm.tsx
  client/src/component/common/Button.tsx
  client/src/component/common/Modal/Modal.tsx
  client/src/component/common/TextInput.tsx
  client/src/component/common/Textarea.tsx
  client/src/hook/useStringWithValidation.ts
  client/src/page/OAuth/OAuthLink.tsx
  client/src/page/Posts/UpsertPostPage.tsx
  client/src/page/UITest.tsx
  client/src/page/User/CheckPassword.tsx
  client/src/page/User/EmailRegistration.tsx
  client/src/page/User/Join.tsx
  client/src/page/User/Login.tsx
  client/src/page/User/ProfileUpdate.tsx
Labels: front-end
