Repository programmers-kdt-full-stack-3rd/community-board, pull requests merged in 2024-07, with the labels that each got.

#5 Feature/posts context
  .gitignore
  server/db/context/posts_context.js
  server/db/sql/comments.sql
  server/db/sql/posts.sql
Labels: back-end

#7 feat: refresh_token 테이블 추가
  server/db/sql/refresh_tokens.sql
Labels: schema

#9 feat : error handling middleware 추가
  server/app.js
  server/utils/errors.js
Labels: back-end

#17 Feature/posts model
  server/controller/posts_controller.ts
  server/db/connect.ts
  server/db/context/posts_context.ts
  server/db/mapper/posts_mapper.ts
  server/db/model/posts.ts
  server/route/posts_router.ts
  server/route/route.ts
Labels: back-end

#20 fix: error 핸들러 작동안하는 문제 수정
  server/app.ts
Labels: bug

#18 Feature/api get comments by post
  server/controller/comments_controller.ts
  server/db/context/comment_context.ts
  server/db/mapper/comments_mapper.ts
  server/db/model/comments.ts
  server/route/comments_router.ts
  server/route/route.ts
Labels: back-end

#21 Feature/api user join
  server/controller/users_controller.ts
  server/db/context/users_context.ts
  server/middleware/validate.ts
  server/package.json
  server/route/route.ts
  server/route/users_router.ts
  server/utils/crypto.ts
Labels: back-end

#25 fix: 게시글, 댓글, 좋아요 테이블 timestamp 컬럼 자동 초기화, 갱신
  server/db/sql/comments.sql
  server/db/sql/posts.sql
Labels: bug, schema

#28 Feature/add new post
  server/controller/posts_controller.ts
  server/db/context/posts_context.ts
  server/route/posts_router.ts
Labels: back-end

#29 Feature/api user login
  server/controller/users_controller.ts
  server/db/context/token_context.ts
  server/db/context/users_context.ts
  server/db/model/users.ts
  server/package.json
  server/route/users_router.ts
  server/utils/token.ts
Labels: back-end

#31 [BE] 댓글 생성 API 구현
  server/controller/comments_controller.ts
  server/db/context/comment_context.ts
  server/route/comments_router.ts
Labels: back-end

#32 Feature/patch post
  server/controller/posts_controller.ts
  server/db/context/posts_context.ts
  server/route/posts_router.ts
Labels: back-end

#37 Feature/delete post
  server/controller/posts_controller.ts
  server/db/context/posts_context.ts
  server/route/posts_router.ts
Labels: back-end

#34 Feature/auth middleware
  server/app.ts
  server/db/context/token_context.ts
  server/middleware/auth.ts
  server/middleware/errors.ts
  server/package.json
  server/tsconfig.json
  server/types/express.d.ts
  server/utils/token.ts
Labels: back-end

#38 [BE] 댓글 수정 API 구현 및 댓글 API 일관성 향상
  server/controller/comments_controller.ts
  server/db/context/comments_context.ts
  server/route/comments_router.ts
Labels: back-end

#40 Feature/api logout
  server/controller/users_controller.ts
  server/db/context/token_context.ts
  server/route/users_router.ts
Labels: back-end

#44 [BE] 댓글 삭제 API 구현
  server/controller/comments_controller.ts
  server/db/context/comments_context.ts
  server/route/comments_router.ts
Labels: back-end

#48 [BE] 비밀번호 확인 API 구현
  server/controller/users_controller.ts
  server/db/context/users_context.ts
  server/middleware/auth.ts
  server/route/users_router.ts
  server/utils/token.ts
Labels: back-end

#46 [BE] 회원 정보 수정 API 구현
  server/controller/users_controller.ts
  server/db/context/users_context.ts
  server/middleware/auth.ts
  server/route/users_router.ts
  server/utils/token.ts
Labels: back-end

#52 [BE] 댓글 context의 DB 쿼리 보완
  server/db/context/comments_context.ts
Labels: bug, back-end

#53 Feature/http request function
  client/src/api/api.ts
  client/src/api/test/test.ts
  client/src/component/Posts/Posts.tsx
  client/src/component/TestMain/TestMain.tsx
  server/controller/testController.ts
  server/route/route.ts
Labels: back-end

#51 [BE] 회원 탈퇴 API 구현
  server/controller/users_controller.ts
  server/db/context/token_context.ts
  server/db/context/users_context.ts
  server/middleware/auth.ts
  server/route/users_router.ts
Labels: back-end

#56 [BE] user_router 유효성 검사 리팩토링
  server/route/users_router.ts
  server/utils/validations/users/constants.ts
  server/utils/validations/users/user.ts
Labels: back-end

#57 [Refacotor] 게시글 목록 불러오기에 정렬 추가
  client/package.json
  client/src/App.tsx
  client/src/api/posts/crud.ts
  client/src/component/Posts/Posts.tsx
  client/src/component/TestMain/TestMain.tsx
  client/src/component/TestMain/Tests.tsx
  package.json
  server/controller/posts_controller.ts
  server/db/context/posts_context.ts
  server/package.json
  shared/index.ts
  shared/package.json
  shared/posts/enums.ts
Labels: back-end

#58 refactor : delete -> update isDelete = true
  server/db/context/posts_context.ts
Labels: back-end

#59 Refactor/use token middleware
  server/controller/posts_controller.ts
  server/route/posts_router.ts
Labels: back-end

#61 [BE] 댓글 API URL 변경 및 유효성 검사 리팩터링
  server/controller/comments_controller.ts
  server/route/comments_router.ts
  server/utils/validations/comments/comment.ts
  server/utils/validations/comments/constants.ts
Labels: back-end

#63 refactor : posts validation 정리
  server/route/posts_router.ts
  server/utils/validations/posts/constants.ts
  server/utils/validations/posts/posts.ts
Labels: back-end

#67 [FE] client package 추가
  client/package.json
  client/src/App.css.ts
  client/vite.config.ts
Labels: back-end

#64 [BE] 게시글, 댓글 좋아요 API
  server/controller/comments_controller.ts
  server/controller/likes_controller.ts
  server/controller/posts_controller.ts
  server/db/context/comments_context.ts
  server/db/context/likes_context.ts
  server/db/context/posts_context.ts
  server/db/mapper/comments_mapper.ts
  server/db/mapper/likes_mapper.ts
  server/db/mapper/posts_mapper.ts
  server/db/model/comments.ts
  server/db/model/likes.ts
  server/db/model/posts.ts
  server/db/sql/comments.sql
  server/db/sql/posts.sql
  server/route/likes_router.ts
  server/route/route.ts
  server/utils/validations/likes/constants.ts
  server/utils/validations/likes/like.ts
Labels: back-end

#72 [BE] 로그인 API response 내용 추가
  server/controller/users_controller.ts
  server/db/context/users_context.ts
Labels: back-end

#74 [FE] 게시글 생성/수정 모달
  client/src/App.css.ts
  client/src/api/posts/crud.ts
  client/src/component/Posts/Modal/PostModal.css.ts
  client/src/component/Posts/Modal/PostModal.tsx
  client/src/component/Posts/Posts.tsx
Labels: front-end

#75 [BE] 게시글, 댓글 조회 API 응답에 is_author 필드 추가
  server/db/context/comments_context.ts
  server/db/context/posts_context.ts
  server/db/mapper/comments_mapper.ts
  server/db/mapper/posts_mapper.ts
  server/db/model/comments.ts
  server/db/model/posts.ts
Labels: back-end

#76 [FE] 로그인 화면 구현
  client/src/App.tsx
  client/src/api/users/crud.ts
  client/src/component/User/User.tsx
  client/src/page/User/Login.css.ts
  client/src/page/User/Login.tsx
  client/src/page/User/User.tsx
Labels: front-end

#79 [FE] zustand 세팅
  client/package.json
  client/src/component/TestMain/Tests.tsx
  client/src/page/User/Login.tsx
  client/src/state/selector.ts
  client/src/state/store.ts
  server/controller/users_controller.ts
Labels: setting, front-end

#81 [FE] 로그인 화면 리펙토링
  client/src/App.tsx
  client/src/component/User/EmailForm.css.ts
  client/src/component/User/EmailForm.tsx
  client/src/component/User/ErrorMessageForm.tsx
  client/src/component/User/InputField.css.ts
  client/src/component/User/InputField.tsx
  client/src/component/User/PasswordForm.tsx
  client/src/component/User/SubmitButton.css.ts
  client/src/component/User/SubmitButton.tsx
  client/src/page/User/Join.tsx
  client/src/page/User/Login.css.ts
  client/src/page/User/Login.tsx
  client/src/page/User/User.tsx
Labels: front-end

#83 [FE] 회원가입 페이지 구현
  client/src/api/users/crud.ts
  client/src/component/User/ErrorMessageForm.tsx
  client/src/component/User/InputField.tsx
  client/src/component/User/NicknameForm.tsx
  client/src/component/User/PasswordForm.tsx
  client/src/component/User/SubmitButton.tsx
  client/src/component/User/css/InputField.css.ts
  client/src/component/User/css/SubmitButton.css.ts
  client/src/component/User/css/errorMessage.css.ts
  client/src/page/User/Join.css.ts
  client/src/page/User/Join.tsx
  client/src/page/User/Login.tsx
  client/src/page/User/constants/constants.ts
  server/db/context/users_context.ts
  server/utils/validations/users/user.ts
Labels: front-end

#82 [FE] 게시글 정보 컴포넌트
  client/package.json
  client/src/App.tsx
  client/src/component/Posts/PostInfo.css.ts
  client/src/component/Posts/PostInfo.tsx
  client/src/component/Posts/Posts.tsx
  client/src/page/Posts/PostInfoPage.css.ts
  client/src/page/Posts/PostInfoPage.tsx
  client/src/utils/date-to-str.tsx
  server/db/context/posts_context.ts
  shared/index.ts
  shared/posts/mappers.ts
  shared/posts/models.ts
Labels: front-end

#84 fix : IPostInfo에 is_author가 추가되어 발생한 타입 오류 수정
  client/src/page/Posts/PostInfoPage.tsx
Labels: bug

#86 [FE] state 값을 로컬 스토리지에 저장
  client/src/page/User/Login.tsx
  client/src/state/store.ts
Labels: front-end

#88 [FE] 메인 페이지(게시글 목록) 컴포넌트 구현
  client/src/App.css
  client/src/App.tsx
  client/src/component/Posts/PostList/PostList.css.ts
  client/src/component/Posts/PostList/PostList.tsx
  client/src/component/common/Pagination/Pagination.css.ts
  client/src/component/common/Pagination/Pagination.tsx
  client/src/component/common/SearchForm/SearchForm.css.ts
  client/src/component/common/SearchForm/SearchForm.tsx
  client/src/hook/useMainPageSearchParams.ts
  client/src/page/Main/Main.css.ts
  client/src/page/Main/Main.tsx
  client/src/utils/clamp.ts
Labels: front-end

#89 fix : 조회수 기준 정렬 버그 + post_header field에 views 추가
  server/db/context/posts_context.ts
  shared/posts/enums.ts
  shared/posts/mappers.ts
Labels: bug, back-end

#93 [FE] 헤더 추가를 위한 전역 스타일 변경
  client/src/App.css
  client/src/App.css.ts
  client/src/App.tsx
  client/src/component/Header/Header.css.ts
  client/src/component/Header/Header.tsx
  client/src/component/TestMain/TestMain.css.tsx
  client/src/component/TestMain/TestMain.tsx
  client/src/index.css
  client/src/root.css.ts
Labels: front-end

#94 [FE] 사이트 헤더 구현
  client/src/App.tsx
  client/src/api/users/crud.ts
  client/src/component/Header/Header.css.ts
  client/src/component/Header/Header.tsx
  client/src/page/User/Login.tsx
Labels: front-end

#95 [FE] 게시글 내용 보기 페이지2
  client/src/api/likes/crud.ts
  client/src/api/posts/crud.ts
  client/src/component/Posts/Modal/DeleteModal.css.ts
  client/src/component/Posts/Modal/DeleteModal.tsx
  client/src/component/Posts/Modal/PostModal.css.ts
  client/src/component/Posts/Modal/PostModal.tsx
  client/src/component/Posts/PostInfo.css.ts
  client/src/component/Posts/PostInfo.tsx
Labels: front-end

#99 [FE] 회원 정보 클릭시 드랍다운메뉴 추가
  client/src/App.tsx
  client/src/api/users/crud.ts
  client/src/component/Header/DropdownMenu.css.ts
  client/src/component/Header/DropdownMenu.tsx
  client/src/component/Header/Header.tsx
  client/src/page/User/CheckPassword.css.ts
  client/src/page/User/CheckPassword.tsx
  client/src/page/User/User.tsx
Labels: front-end

#100 [FE] 회원정보 수정 페이지 추가
  client/src/App.tsx
  client/src/api/users/crud.ts
  client/src/page/User/ProfileUpdate.css.ts
  client/src/page/User/ProfileUpdate.tsx
  client/src/page/User/User.tsx
  server/controller/users_controller.ts
  server/middleware/auth.ts
Labels: front-end

#101 [FE] 댓글 목록 컴포넌트 기본 구조, 댓글 목록 읽기
  client/src/api/comments/crud.ts
  client/src/component/Comments/CommentItem/CommentItem.css.ts
  client/src/component/Comments/CommentItem/CommentItem.tsx
  client/src/component/Comments/CommentLikeButton/CommentLikeButton.css.ts
  client/src/component/Comments/CommentLikeButton/CommentLikeButton.tsx
  client/src/component/Comments/Comments.css.ts
  client/src/component/Comments/Comments.tsx
  client/src/page/Posts/PostInfoPage.tsx
  server/db/context/comments_context.ts
  shared/comments/mappers.ts
  shared/comments/models.ts
  shared/index.ts
Labels: front-end

#102 [FE] 회원탈퇴 확인 모달 추가
  client/src/api/users/crud.ts
  client/src/component/Header/DropdownMenu.tsx
  client/src/component/Header/Header.tsx
  client/src/component/Header/UserDeleteModal.css.ts
  client/src/component/Header/UserDeleteModal.tsx
  client/src/hook/useModal.ts
  client/src/page/User/CheckPassword.tsx
  client/src/page/User/User.tsx
Labels: front-end

#103 [FE] 댓글 작성, 수정, 삭제, 좋아요
  client/src/api/likes/crud.ts
  client/src/component/Comments/CommentForm/CommentForm.css.ts
  client/src/component/Comments/CommentForm/CommentForm.tsx
  client/src/component/Comments/CommentItem/CommentItem.css.ts
  client/src/component/Comments/CommentItem/CommentItem.tsx
  client/src/component/Comments/CommentLikeButton/CommentLikeButton.tsx
  client/src/component/Comments/Comments.css.ts
  client/src/component/Comments/Comments.tsx
Labels: front-end

#104 [FE] 메인 페이지의 게시글 목록 정보 보충
  client/src/component/Posts/PostList/EmptyPostListBody.tsx
  client/src/component/Posts/PostList/PostList.css.ts
  client/src/component/Posts/PostList/PostList.tsx
  client/src/page/Main/Main.tsx
  client/src/utils/date-to-str.tsx
  shared/posts/models.ts
Labels: front-end

#107 [FE] 회원 관련 화면 레이아웃 중앙 정렬 구현
  client/src/App.css.ts
  client/src/App.tsx
Labels: front-end

#110 feat : 게시글 내용 조회 기능에 조회수 증가 로직 추가
  server/db/context/posts_context.ts
Labels: back-end

#111 [FE]client login 상태 관리
  client/src/api/api.ts
  client/src/component/Header/Header.tsx
  client/src/page/User/CheckPassword.tsx
  server/middleware/auth.ts
Labels: back-end, front-end

#112 [FE] httpRequest의 error handling 함수 추가
  client/src/App.tsx
  client/src/api/api.ts
  client/src/api/errors.ts
  client/src/api/users/utils.ts
  client/src/component/Comments/CommentItem/CommentItem.tsx
  client/src/component/Comments/Comments.tsx
  client/src/component/Posts/Modal/PostModal.tsx
  client/src/component/utils/ErrorModal.css.ts
  client/src/component/utils/ErrorModal.tsx
  client/src/state/errorModalStore.ts
Labels: front-end

#114 향후 작업 항목 목록 해결
  client/src/component/User/EmailForm.tsx
  client/src/component/User/InputField.tsx
  client/src/component/User/NicknameForm.tsx
  client/src/component/User/PasswordForm.tsx
  client/src/component/User/css/InputField.css.ts
  client/src/page/User/Join.tsx
  client/src/page/User/Login.tsx
  server/controller/users_controller.ts
  server/db/context/users_context.ts
  server/db/sql/users.sql
  server/middleware/auth.ts
  server/route/users_router.ts
  server/utils/validations/users/constants.ts
  server/utils/validations/users/user.ts
Labels: back-end, front-end

#117 [FE] 유저 API에 에러 핸들링 함수 적용
  client/src/api/api.ts
  client/src/component/Header/Header.tsx
  client/src/page/User/CheckPassword.tsx
  client/src/page/User/Join.tsx
  client/src/page/User/Login.tsx
  client/src/page/User/ProfileUpdate.tsx
Labels: front-end

#118 [FE] ApiCall 을 comment, post, like에 적용하기
  client/src/App.tsx
  client/src/component/Comments/CommentLikeButton/CommentLikeButton.tsx
  client/src/component/Posts/Modal/DeleteModal.tsx
  client/src/component/Posts/PostInfo.tsx
  client/src/component/Posts/Posts.tsx
  client/src/page/Main/Main.tsx
  client/src/page/Posts/PostInfoPage.tsx
  client/src/page/User/User.tsx
Labels: front-end

#119 댓글 목록 페이지네이션 구현
  client/src/App.css.ts
  client/src/api/comments/crud.ts
  client/src/component/Comments/CommentItem/CommentItem.tsx
  client/src/component/Comments/Comments.css.ts
  client/src/component/Comments/Comments.tsx
  server/controller/comments_controller.ts
  server/db/context/comments_context.ts
Labels: back-end, front-end

#120 비속어 필터링 기능 추가
  client/src/App.css.ts
  client/src/component/Posts/Modal/PostModal.css.ts
  client/src/component/Posts/Modal/PostModal.tsx
  server/controller/posts_controller.ts
  server/db/context/posts_context.ts
  server/tsconfig.json
  server/utils/bad-word-regex/README.md
  server/utils/bad-word-regex/constants.ts
  server/utils/bad-word-regex/fillRegexs.ts
  server/utils/bad-word-regex/regexTask.ts
  server/utils/bad-word-regex/regexs.json
  server/utils/bad-word-regex/testCase.ts
Labels: back-end, front-end
