Repository programmers-kdt-full-stack-3rd/community-board, pull requests merged in 2024-11, with the labels that each got.

#331 🐛 [fix] : 다크모드에서 TextInput 컴포넌트 invalid 상태 시인성 개선
  client/src/component/common/TextInput.tsx
Labels: front-end

#330 ♻️ [refactor] : user api 리팩토링
  client/src/api/api.ts
  client/src/api/users/crud.ts
  client/src/component/Header/Header.tsx
  client/src/component/Header/UserDropdown.tsx
  client/src/component/Profile/Modal/PasswordUpdateModal.tsx
  client/src/component/User/OAuthLoginButtons.tsx
  client/src/page/Profile/ProfilePage.tsx
  client/src/page/User/CheckPassword.tsx
  client/src/page/User/EmailRegistration.tsx
  client/src/page/User/Join.tsx
  client/src/page/User/Login.tsx
  client/src/page/User/ProfileUpdate.tsx
  nestjs-migration/src/user/user.controller.ts
  shared/community/api.ts
  shared/community/users/users_api.ts
  sql/14_user_logs.sql
  sql/15_recruting_posts.sql
Labels: back-end, front-end

#333 🚀 [chore] : 코드 포맷 검사 스크립트 추가
  chat_server/package.json
  client/package.json
  client/postcss.config.cjs
  client/src/api/admin/post_crud.ts
  client/src/api/admin/user_crud.ts
  client/src/component/Admin/UserLog/UserLog.ts
  client/src/utils/date-to-str.tsx
  consumer-server/package.json
  migration-test/package.json
  migration-test/tsconfig.build.json
  nestjs-migration/package.json
  package.json
  server/package.json
  shared/package.json
Labels: setting

#334 ♻️🐛 [refactor/fix] : Chat server 모듈화 및 이벤트 수정과 버그 수정
  chat_server/app.ts
  chat_server/config/index.ts
  chat_server/config/kafka.config.ts
  chat_server/config/redis.config.ts
  chat_server/config/socket.config.ts
  chat_server/controllers/chat.controller.ts
  chat_server/controllers/chat_controller.ts
  chat_server/controllers/notification_controller.ts
  chat_server/controllers/room.controller.ts
  chat_server/events/chat.event.ts
  chat_server/events/chatroom_events.ts
  chat_server/events/message_events.ts
  chat_server/events/notification_events.ts
  chat_server/events/room.event.ts
  chat_server/index.ts
  chat_server/middlewares/auth.middleware.ts
  chat_server/package.json
  chat_server/services/chat.service.ts
  chat_server/services/chat_service.ts
  chat_server/services/chatroom_service.ts
  chat_server/services/kafka_service.ts
  chat_server/services/message_service.ts
  chat_server/services/redis.service.ts
  chat_server/services/room.service.ts
  chat_server/utils/api.ts
  chat_server/utils/kafka.ts
  chat_server/utils/redis.ts
  client/src/App.tsx
  client/src/component/Chats/ChatRoom/ChatRoom.tsx
  client/src/component/Chats/ChatRooms/ChatRooms.tsx
  client/src/component/Chats/ChatRooms/MyChatRooms.tsx
  client/src/component/Chats/ChatRooms/Rooms/Room.tsx
  client/src/state/store.ts
  shared/chat/chat_api.ts
  shared/chat/chats.ts
Labels: back-end, front-end

#335 ✨ [feat] : Toast 컴포넌트 작성 및 일부 모달을 토스트로 대체
  client/index.html
  client/src/App.tsx
  client/src/component/Chats/ChatRoom/SideBar/ChatRoomSideBar.tsx
  client/src/component/Coupon/coupon.tsx
  client/src/component/Posts/Editer/ImageManager.tsx
  client/src/component/Posts/PostInfo.tsx
  client/src/component/Profile/Modal/PasswordUpdateModal.tsx
  client/src/component/User/OAuthLoginButtons.tsx
  client/src/component/common/Toast/Toast.tsx
  client/src/component/common/Toast/ToastItem.tsx
  client/src/page/Profile/ProfilePage.tsx
  client/src/page/User/CheckPassword.tsx
  client/src/page/User/EmailRegistration.tsx
  client/src/page/User/Join.tsx
  client/src/page/User/Login.tsx
  client/src/page/User/ProfileUpdate.tsx
  client/src/state/ToastStore.ts
  client/src/vite-env.d.ts
Labels: front-end
