Repository programmers-kdt-full-stack-3rd/community-board, pull requests merged in 2024-08, with the labels that each got.

#121 채팅방 (채팅 aside) UI 추가
  client/src/App.tsx
  client/src/component/Chats/ChatRoom.tsx
  client/src/component/Chats/ChatRoom/ChatInput.tsx
  client/src/component/Chats/ChatRoom/ChatRoom.css.ts
  client/src/component/Chats/ChatRoom/ChatRoom.tsx
  client/src/component/Chats/ChatRoom/ChatRoomHeader.tsx
  client/src/component/Chats/ChatRoom/MyChat.tsx
  client/src/component/Chats/ChatRoom/SystemChat.tsx
  client/src/component/Chats/ChatRoom/YourChat.tsx
Labels: front-end

#122 검색 채팅방 리스트 & 내 채팅방 리스트(채팅 aside) UI 추가
  client/src/App.tsx
  client/src/component/Chats/ChatRooms.tsx
  client/src/component/Chats/ChatRooms/ChatRooms.css.ts
  client/src/component/Chats/ChatRooms/ChatRooms.tsx
  client/src/component/Chats/ChatRooms/Rooms/Rooms.css.ts
  client/src/component/Chats/ChatRooms/Rooms/Rooms.tsx
Labels: front-end

#123 채팅방 (채팅 aside) 메세지 렌더링 기능
  client/src/component/Chats/ChatRoom/ChatRoom.tsx
Labels: front-end

#124 Feature/add chat rooms enter logic
  client/src/component/Chats/ChatRooms/Rooms/Room.tsx
  client/src/component/Chats/ChatRooms/Rooms/Rooms.css.ts
  client/src/component/Chats/ChatRooms/Rooms/Rooms.tsx
Labels: front-end

#125 채팅방 리스트 pagination 추가
  client/src/component/Chats/ChatRooms/ChatRooms.tsx
  client/src/component/Chats/ChatRooms/Pagenation/Pagenation.tsx
  client/src/component/Chats/ChatRooms/Pagenation/pagenation.css.ts
Labels: front-end

#127 [BE] 권한 분리 시스템 구현 (RBAC)
  server/db/context/permissions_context.ts
  server/db/context/roles_context.ts
  server/db/context/roles_permission_context.ts
  server/db/context/users_context.ts
  server/db/model/rbac.ts
  server/db/sql/permissions.sql
  server/db/sql/role_permission.sql
  server/db/sql/roles.sql
  server/db/sql/setup_rbac.sql
  server/db/sql/users.sql
  server/utils/rbac.ts
Labels: schema, back-end

#137 소켓 서버 구축
  chat_server/app.ts
  chat_server/controllers/chat_controller.ts
  chat_server/controllers/notification_controller.ts
  chat_server/events/chatroom_events.ts
  chat_server/events/message_events.ts
  chat_server/events/notification_events.ts
  chat_server/package.json
  chat_server/services/chatroom_service.ts
  chat_server/services/message_service.ts
  chat_server/tsconfig.json
  chat_server/types/chatroom.d.ts
  chat_server/types/message.d.ts
  package.json
Labels: back-end

#141 [BE] kafka & redis 개발환경 및 프로젝트 세팅
  .gitignore
  chat_server/app.ts
  chat_server/config/kafka_config.ts
  chat_server/config/redis_config.ts
  chat_server/package.json
  chat_server/services/cache_service.ts
  chat_server/services/kafka_service.ts
  consumer-server/package.json
  consumer-server/src/config/dbConfig.ts
  consumer-server/src/config/kafkaConfig.ts
  consumer-server/src/index.ts
  consumer-server/src/models/chatMessageModel.ts
  consumer-server/src/services/kafkaService.ts
  docker-compose.yaml
  package.json
Labels: back-end

#130 [BE] 어드민용 사용자 목록 조회 API 구현
  server/controller/admin_controller.ts
  server/db/context/users_context.ts
  server/db/mapper/users_mapper.ts
  server/db/model/users.ts
  server/db/sql/users.sql
  server/route/admin_router.ts
  server/route/route.ts
Labels: back-end

#135 [BE] 사용자 계정 삭제/복구 API 구현
  server/controller/admin_controller.ts
  server/db/context/users_context.ts
  server/route/admin_router.ts
  server/utils/validations/admin/admin.ts
  server/utils/validations/admin/constants.ts
Labels: back-end

#139 [BE] 게시글 목록 조회 API 구현
  server/controller/admin_controller.ts
  server/db/context/posts_context.ts
  server/db/mapper/posts_mapper.ts
  server/db/model/posts.ts
  server/db/sql/posts.sql
  server/route/admin_router.ts
Labels: back-end

#150 [채팅] 채팅방 생성 기능
  client/src/api/chats/crud.ts
  client/src/component/Chats/ChatRooms/ChatRooms.tsx
  client/src/component/Chats/ChatRooms/Modal/CreateRoomModal.css.ts
  client/src/component/Chats/ChatRooms/Modal/CreateRoomModal.tsx
  client/src/component/Chats/ChatRooms/Rooms/Room.tsx
  client/src/component/Chats/ChatRooms/Rooms/Rooms.tsx
  client/src/component/Chats/ChatRooms/test-case.ts
  server/controller/chats_controller.ts
  server/db/context/chats_context.ts
  server/db/sql/chats.sql
  server/route/chats_router.ts
  server/route/route.ts
  shared/chats/chat-room.ts
  shared/chats/dto.ts
  shared/chats/mappers.ts
Labels: back-end, front-end

#155 [채팅] 채팅방 조회 기능
  client/src/api/chats/crud.ts
  client/src/component/Chats/ChatRooms/ChatRooms.tsx
  client/src/component/Chats/ChatRooms/Pagenation/Pagenation.tsx
  client/src/utils/detectMode.ts
  server/controller/chats_controller.ts
  server/db/context/chats_context.ts
  server/route/chats_router.ts
  shared/chats/mappers.ts
Labels: back-end, front-end

#160 [BE] 메시지 큐 구현
  .gitignore
  chat_server/app.ts
  chat_server/config/kafka_config.ts
  chat_server/config/redis_config.ts
  chat_server/index.ts
  chat_server/package.json
  chat_server/services/kafka_service.ts
  consumer-server/src/config/dbConfig.ts
  consumer-server/src/config/kafkaConfig.ts
  consumer-server/src/index.ts
  consumer-server/src/models/chatMessageModel.ts
  consumer-server/src/services/kafkaService.ts
  consumer-server/src/services/messageService.ts
  docker-compose.yaml
  server/db/sql/chats.sql
  shared/chats/dto.ts
Labels: back-end

#164 내 채팅방 리스트 조회, 채팅방 검색 기능 완성
  client/src/component/Chats/ChatRooms/ChatRooms.tsx
  client/src/component/Chats/ChatRooms/MyChatRooms.tsx
  client/src/component/Chats/ChatRooms/Pagenation/Pagenation.tsx
  client/src/component/Chats/ChatRooms/SearchedChatRooms.tsx
Labels: front-end

#166 [채팅] 메세지 기록 조회 API
  .gitignore
  client/src/component/Chats/ChatRooms/SearchedChatRooms.tsx
  server/controller/chats_controller.ts
  server/db/context/chats_context.ts
  server/db/sql/chats.sql
  server/route/chats_router.ts
  shared/chats/dto.ts
  shared/chats/mappers.ts
  shared/chats/message.ts
Labels: back-end

#167 [채팅] 채팅방 가입 기능 api
  server/controller/chats_controller.ts
  server/db/context/chats_context.ts
  server/route/chats_router.ts
  shared/chats/chat-room.ts
Labels: back-end

#168 [채팅] 채팅방 별 멤버 리스트 조회 api
  server/controller/chats_controller.ts
  server/db/context/chats_context.ts
  server/route/chats_router.ts
  shared/chats/dto.ts
  shared/chats/mappers.ts
Labels: back-end

#148 [BE] 관리자용 게시물 삭제/복구 및 공개/비공개 API 구현
  server/controller/admin_controller.ts
  server/db/context/posts_context.ts
  server/route/admin_router.ts
  server/utils/validations/admin/admin.ts
  server/utils/validations/admin/constants.ts
  server/utils/validations/posts/posts.ts
  server/utils/validations/users/user.ts
Labels: back-end

#176 🐛 [fix] : dto 변경에 따른 테스트 케이스 타입 에러 수정
  client/src/component/Chats/ChatRooms/test-case.ts
Labels: front-end

#174 [FE] 사용자 관리 게시판 구현
  client/src/App.tsx
  client/src/component/Admin/AdminSidebar.css.ts
  client/src/component/Admin/AdminSidebar.tsx
  client/src/component/Admin/UserMgmt/EmptyUserList.tsx
  client/src/component/Admin/UserMgmt/UserList.css.ts
  client/src/component/Admin/UserMgmt/UserList.tsx
  client/src/component/Header/DropdownMenu.tsx
  client/src/page/Admin/AdminPostMgmtPage.tsx
  client/src/page/Admin/AdminStatsPage.tsx
  client/src/page/Admin/AdminUserMgmtPage.css.ts
  client/src/page/Admin/AdminUserMgmtPage.tsx
  shared/admin/users.ts
  shared/index.ts
Labels: front-end

#173 [FE] 게시글 관리 게시판 구현
  client/src/component/Admin/PostMgmt/EmptyPostList.tsx
  client/src/component/Admin/PostMgmt/PostMgmt.css.ts
  client/src/component/Admin/PostMgmt/PostMgmt.tsx
  client/src/component/Admin/PostMgmt/PostMgmtAction.ts
  client/src/component/Admin/PostMgmt/PostMgmtItem.tsx
  client/src/component/Admin/UserMgmt/UserList.tsx
  client/src/page/Admin/AdminPostMgmtPage.tsx
  client/src/page/Admin/AdminUserMgmtPage.tsx
  shared/admin/posts.ts
  shared/index.ts
Labels: front-end

#177 로그인/로그아웃, 소켓 연결
  chat_server/app.ts
  client/package.json
  client/src/App.tsx
  client/src/component/Header/Header.tsx
Labels: back-end

#171 [BE] 유저별 통계 데이터 API 구현
  server/controller/admin_controller.ts
  server/db/context/stats_context.ts
  server/db/model/stats.ts
  server/route/admin_router.ts
  server/utils/validations/admin/admin.ts
Labels: back-end

#161 [BE] 전체 통계 데이터 조회 API 구현
  server/controller/admin_controller.ts
  server/db/context/stats_context.ts
  server/db/mapper/stats_mapper.ts
  server/db/model/stats.ts
  server/route/admin_router.ts
  server/utils/validations/admin/admin.ts
Labels: back-end

#153 [BE] 사용자 활동 로그 기능 구현
  server/controller/admin_controller.ts
  server/controller/comments_controller.ts
  server/controller/posts_controller.ts
  server/db/context/comments_context.ts
  server/db/context/logs_context.ts
  server/db/context/posts_context.ts
  server/db/context/stats_context.ts
  server/db/context/users_context.ts
  server/db/mapper/logs_mapper.ts
  server/db/mapper/stats_mapper.ts
  server/db/model/logs.ts
  server/db/model/stats.ts
  server/db/model/users.ts
  server/db/sql/user_log_categories.sql
  server/db/sql/user_logs.sql
  server/route/admin_router.ts
  server/utils/text-formatter.ts
  server/utils/user-logs-utils.ts
  server/utils/validations/admin/admin.ts
Labels: back-end

#172 [BE] 소셜 로그인 재확인 관련 API 구현
  server/controller/oauth_controller.ts
  server/route/oauth_router.ts
  server/utils/oauth/constants.ts
  server/utils/oauth/oauth.ts
  server/utils/validations/oauth/oauth.ts
Labels: back-end

#145 [BE] OAuth(소셜 로그인) 로그인, 회원가입 구현
  server/controller/oauth_controller.ts
  server/controller/users_controller.ts
  server/db/context/oauth_context.ts
  server/db/context/users_context.ts
  server/db/mapper/users_mapper.ts
  server/db/sql/oauth.sql
  server/db/sql/users.sql
  server/route/oauth_router.ts
  server/route/route.ts
  server/utils/getKstNow.ts
  server/utils/oauth/constants.ts
  server/utils/oauth/oauth.ts
  server/utils/validations/oauth/constants.ts
  server/utils/validations/oauth/oauth.ts
Labels: schema, back-end

#178 [FE] 소셜 로그인 UI 구현 및 API 연동
  client/package.json
  client/src/App.tsx
  client/src/api/api.ts
  client/src/api/users/oauth.ts
  client/src/assets/icons/google-icon.svg
  client/src/assets/icons/kakao-icon.svg
  client/src/assets/icons/naver-icon.svg
  client/src/component/User/css/InputField.css.ts
  client/src/component/User/css/SubmitButton.css.ts
  client/src/index.css
  client/src/page/OAuthRedirectHandler.tsx
  client/src/page/User/Join.css.ts
  client/src/page/User/Login.css.ts
  client/src/page/User/Login.tsx
Labels: front-end

#175 [채팅] 채팅방 탈퇴 api 구현
  server/controller/chats_controller.ts
  server/db/context/chats_context.ts
  server/route/chats_router.ts
  shared/chats/chat-room.ts
Labels: back-end

#182 [채팅] 채팅 기능을 위한 zustand state와 실제 적용
  client/src/component/Chats/ChatRooms/ChatRooms.tsx
  client/src/component/Chats/ChatRooms/MyChatRooms.tsx
  client/src/component/Chats/ChatRooms/Pagenation/Pagenation.tsx
  client/src/state/ChatRoomStore.ts
Labels: front-end

#183 내가 속한 채팅방 조회 기능 [socket]
  chat_server/events/chatroom_events.ts
  chat_server/package.json
  chat_server/utils/api.ts
  client/src/App.tsx
  client/src/component/Chats/ChatRooms/ChatRooms.tsx
  client/src/component/Chats/ChatRooms/MyChatRooms.tsx
  server/controller/chats_controller.ts
  shared/chats/chat-room.ts
Labels: back-end

#185 [FE/BE] 채팅방 입장 및 실시간 채팅
  chat_server/app.ts
  chat_server/events/chatroom_events.ts
  chat_server/events/message_events.ts
  chat_server/index.ts
  chat_server/package.json
  chat_server/services/api_service.ts
  chat_server/services/kafka_service.ts
  client/.eslintrc.cjs
  client/src/App.tsx
  client/src/component/Chats/ChatRoom/ChatRoom.tsx
  client/src/component/Header/Header.tsx
  client/src/state/store.ts
  shared/chats/dto.ts
  shared/chats/mappers.ts
Labels: back-end, front-end

#194 [채팅-FIX] 여러 문제점 수정
  chat_server/app.ts
  chat_server/events/chatroom_events.ts
  chat_server/utils/api.ts
  client/src/component/Chats/ChatRooms/ChatRooms.tsx
  client/src/component/Chats/ChatRooms/MyChatRooms.tsx
  consumer-server/package.json
  consumer-server/src/index.ts
  server/controller/chats_controller.ts
  server/db/context/chats_context.ts
  server/db/sql/chats.sql
  shared/chats/chat-room.ts
Labels: back-end, front-end

#193 [FE] 로딩 화면, 404 페이지 구현
  client/src/App.tsx
  client/src/component/common/Loader/Loader.css.ts
  client/src/component/common/Loader/Loader.tsx
  client/src/page/OAuthRedirectHandler.tsx
  client/src/page/error/NotFound.css.ts
  client/src/page/error/NotFound.tsx
Labels: front-end

#192 [BE] 회원 탈퇴 시 소셜 로그인 연동 해제
  server/controller/oauth_controller.ts
  server/controller/users_controller.ts
  server/db/context/oauth_context.ts
  server/db/mapper/oauth_mapper.ts
  server/db/model/oauth.ts
  server/db/sql/oauth.sql
  server/utils/oauth/constants.ts
  server/utils/oauth/oauth.ts
  server/utils/validations/oauth/constants.ts
  server/utils/validations/oauth/oauth.ts
Labels: back-end

#190 [FE] 사용자 로그 조회 게시판 구현
  client/src/App.tsx
  client/src/component/Admin/PostMgmt/PostMgmt.css.ts
  client/src/component/Admin/PostMgmt/PostMgmt.tsx
  client/src/component/Admin/PostMgmt/PostMgmtAction.ts
  client/src/component/Admin/PostMgmt/PostMgmtItem.tsx
  client/src/component/Admin/UserLog/UserLog.css.ts
  client/src/component/Admin/UserLog/UserLog.ts
  client/src/component/Admin/UserMgmt/UserList.css.ts
  client/src/component/Admin/UserMgmt/UserList.tsx
  client/src/page/Admin/AdminPostMgmtPage.tsx
  client/src/page/Admin/AdminUserLogPage.tsx
  client/src/page/Admin/AdminUserMgmtPage.tsx
  server/db/context/stats_context.ts
  server/db/mapper/logs_mapper.ts
  server/db/mapper/posts_mapper.ts
  server/db/model/logs.ts
  server/db/model/users.ts
  shared/admin/posts.ts
  shared/admin/users.ts
  shared/index.ts
Labels: front-end

#196 [FE/BE] 채팅방 가입 기능
  chat_server/events/chatroom_events.ts
  chat_server/utils/api.ts
  client/src/App.tsx
  client/src/component/Chats/ChatRoom/ChatRoom.tsx
  client/src/component/Chats/ChatRooms/ChatRooms.tsx
  client/src/component/Chats/ChatRooms/MyChatRooms.tsx
  client/src/component/Chats/ChatRooms/Rooms/Room.tsx
  shared/chats/chat-room.ts
  shared/chats/dto.ts
Labels: back-end, front-end

#198 [FIX-채팅] 채팅 관련 수정
  chat_server/app.ts
  chat_server/events/chatroom_events.ts
  chat_server/events/message_events.ts
  chat_server/index.ts
  chat_server/services/api_service.ts
  chat_server/services/kafka_service.ts
  chat_server/utils/api.ts
  client/src/App.tsx
  client/src/component/Chats/ChatRoom/ChatRoom.css.ts
  client/src/component/Chats/ChatRoom/ChatRoom.tsx
  client/src/component/Chats/ChatRoom/ChatRoomHeader.tsx
  client/src/component/Chats/ChatRooms/ChatRooms.tsx
  client/src/component/Chats/ChatRooms/Modal/CreateRoomModal.tsx
  client/src/component/Chats/ChatRooms/MyChatRooms.tsx
  client/src/component/Chats/ChatRooms/Pagenation/Pagenation.tsx
  client/src/component/Chats/ChatRooms/Rooms/Room.tsx
  client/src/component/Chats/ChatRooms/Rooms/Rooms.tsx
  client/src/component/Chats/ChatRooms/SearchedChatRooms.tsx
  client/src/component/Chats/ChatRooms/test-case.ts
  client/src/component/Header/Header.tsx
  client/src/page/Chat/ChatTestPage.tsx
  consumer-server/src/services/kafkaService.ts
  consumer-server/src/services/messageService.ts
  server/controller/chats_controller.ts
  server/db/context/chats_context.ts
  server/db/sql/chats.sql
  server/route/chats_router.ts
  shared/chats/chat-room.ts
  shared/chats/dto.ts
  shared/chats/mappers.ts
Labels: back-end, front-end

#197 [FE] 관리자 통계 게시판 구현
  client/package.json
  client/src/App.tsx
  client/src/component/Admin/PostMgmt/PostMgmt.tsx
  client/src/component/Admin/Stats/AdminGraph.tsx
  client/src/component/Admin/Stats/ChartData.ts
  client/src/component/Admin/Stats/Stats.css.ts
  client/src/component/Admin/Stats/Stats.tsx
  client/src/component/Admin/UserLog/UserLogItem.tsx
  client/src/component/Admin/UserMgmt/UserList.tsx
  client/src/page/Admin/AdminStatsPage.tsx
  client/src/page/Admin/AdminUserLogPage.tsx
  client/src/utils/date-to-str.tsx
Labels: front-end

#195 [BE] 소셜 로그인 회원 정보 수정, 연동 추가·해제 API 구현
  server/controller/oauth_controller.ts
  server/controller/users_controller.ts
  server/db/context/oauth_context.ts
  server/db/context/users_context.ts
  server/route/oauth_router.ts
  server/route/users_router.ts
  server/utils/oauth/oauth.ts
  server/utils/validations/oauth/oauth.ts
  server/utils/validations/users/user.ts
Labels: back-end
